spring:
  application:
    name: shoppingmall

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

sentry:
  dsn: https://f93fd0bbd617ea140678c14099d604b0@o4509603423125504.ingest.us.sentry.io/4509603447504896
  send-default-pii: true
  environment: production
  traces-sample-rate: 1.0

server:
  port: 8080
