name: Deploy to EC2

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    if: |
      github.event.pull_request.merged == true &&
      github.head_ref == 'develop' &&
      contains(github.event.pull_request.title, '[deploy]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "build/libs/shoppingmall-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/app"

      - name: Upload deploy.sh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "deploy.sh"
          target: "/home/ec2-user/app"

      - name: Run deploy.sh on EC2 with secrets
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/app
            chmod +x deploy.sh
            export SPRING_DATASOURCE_URL="${{ secrets.SPRING_DATASOURCE_URL }}"
            export SPRING_DATASOURCE_USERNAME="${{ secrets.SPRING_DATASOURCE_USERNAME }}"
            export SPRING_DATASOURCE_PASSWORD="${{ secrets.SPRING_DATASOURCE_PASSWORD }}"
            export JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}"
            export JWT_ACCESS_TOKEN_EXPIRATION="${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION }}"
            export JWT_REFRESH_TOKEN_EXPIRATION="${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION }}"
            export TOSS_TEST_CLIENT_KEY="${{ secrets.TOSS_TEST_CLIENT_KEY }}"
            export TOSS_TEST_SECRET_KEY="${{ secrets.TOSS_TEST_SECRET_KEY }}"
            ./deploy.sh
